services:
  transportation-backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: transportation-backend
    networks:
      - team-network

    environment:
      DATABASE_PATH: /app/database/transportation.db
      OLLAMA_URL: http://127.0.0.1:11434
      OLLAMA_MODEL: qwen2.5:0.5b

  transportation-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: transportation-frontend
    ports:
      - "3004:80"
    depends_on:
      - transportation-backend
    networks:
      - team-network

networks:
  team-network:
    driver: bridge
