services:
    order-frontend:
        build: ./frontend
        ports: ["8082:80"]
        depends_on: [order-backend]
        networks: [team-network]

    order-backend:
        build: ./backend
        ports: ["5011:5001"]
        environment:
            DATABASE_SERVICE_URL: http://order-database:5002
            OLLAMA_BASE_URL: http://host.docker.internal:11434/v1
            OLLAMA_MODEL: qwen2.5:0.5b
            MCP_SERVER_URL: http://host.docker.internal:5004
            MCP_ENABLED: "true"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on: [order-database]
        networks: [team-network]

    order-database:
        build: ./database
        ports: ["5012:5002"]
        volumes: [order-database-data:/app/data]
        networks: [team-network]

volumes:
    order-database-data:

networks:
  team-network:
    external: true